### ISSUE TITLE
Make TE more extensible and IoC friendly

### ISSUE THREAD

**Issue by weitzhandler** [TrackableEntities/TrackableEntities.Core#12]
We've already discussed this, but I think it's better I should start posting my issues separately to better keep track of them one by one.

So in this one, I'd like to focus on replacing the extensions with injectable services (such as an `IApplyChangesProvider`, `ILoadRelatedEntitiesProvider` etc.) to be either provided by the IoC container, or initialized with the default implementation which implements the respective interfaces.

I'm planning on a PR soon, and I'd appreciate any specific implementation guidelines, conditions or ides.

**Comment by tonysneed** [comment]
Right now TE for .NET Core only has the server bits, so for the client we're still using classic TE, mainly because of the time required to redesign the client change tracker and the code gen that goes with it.

Let's think about what kinds of things we want to make extensible on the server side.  One thing to keep in mind is that TE Core depends directly on EF Core for things like graph traversal.  So it's actually much simpler and can make use of interfaces surfaced by EF Core.

The other thing to keep in mind is that EF Core is very much a moving target.  In particular they are bringing things out of the Internal namespace and refactoring many of the API's.  So we'll want to create a branch that depends on the current EF Core bits.

**Comment by weitzhandler** [comment]
Try to checkout my PR (#13) in VS.
Should you like the idea and I'll keep on finishing it up, and introduce some tests.

What I did is I left the extensions intact, but they're now using the default providers, which can be resolved using the IoC container.
In essence, we wouldn't want to use the extensions at all, instead we want to get all providers from the container and call `provider.LoadRelatedEntities`, where the `DbContext` was already injected to the provider.

We can make another interface that centralizes all providers, for instance:

    interface ITrackableEntitiesProvider
    {
      IApplyChangesProvider GetApplyChangesProvider();
      ILoadRelatedEntitiesProvider GetLoadRelatedEntitiesProvider();       
    }

Maybe I'd have to name it `Service` instead of `Provider`, but first tell me if you like the overall idea, then if you do, I'll move forward moving around the XML docs. And we would also wanna use the same idea in the client side.
I prefer moving on doing concrete things than just prototyping trasheable ideas.

**Comment by tonysneed** [comment]
I'm going to give some thought to this issue over the weekend when I will have a closer look at #13.

**Comment by tonysneed** [comment]
Now that I'm come up for oxygen, I'm going to think more carefully about opening up extensibility points and making it more DI friendly.  I'd like to bring in my colleague @lelong37 (his [URF framework](https://github.com/urfnet) has a dependency on TE) to white board some scenarios where we get the most benefit from a new architecture.

**Comment by tonysneed** [comment]
Deferring this issue until there are some concrete use-cases for adding extensibility points using the strategy pattern. See my [comment](https://github.com/TrackableEntities/TrackableEntities.Core/pull/13#issuecomment-454149982) on #13.
