### ISSUE TITLE
Release  Date

### ISSUE THREAD

**Issue by fbuttazzi** [TrackableEntities/TrackableEntities.Core#15]
Hi Tony,

I am a developer from Brazil, employed in medium developer company.
I want use your project in a real project, but i can´t because your package is in Beta version.
You have any Date for first release?
If not, Why?
If need help for development any enhancement or bug correction for release first version, please tell me,i and my sttaffs can help.
I have great interesting in a release version of this nugget package, because this implementation save many hours when need save complex entities.

PS: My English isn't good, I apologizes by any mistakes.

**Comment by tonysneed** [comment]
Hello! I was waiting for EF 2.1 to be release, but I can release an RC version. Would you be able to use that?

**Comment by fbuttazzi** [comment]
Yes, i apreciate if you make a release. It is important because my company
don't permit using beta version in production enviroment.
Thanks for all.

Fabrizio Buttazzi.

**Comment by tonysneed** [comment]
I released v1.0.0-rc today. You can find the packages here:
- TrackableEntities.Common.Core: https://www.nuget.org/packages/TrackableEntities.Common.Core/1.0.0-rc
- TrackableEntities.EF.Core: https://www.nuget.org/packages/TrackableEntities.EF.Core/1.0.0-rc

I hope this helps.  When EF Core v2.1 comes out, I will align Trackable Entities with it, especially since it raises API's I depend on from the Internal namespace, and it will include I PR I submitted that improved the tooling experience, allowing DbContext and Entities to be generated into different projects.
