### ISSUE TITLE
Port Client to Core

### ISSUE THREAD

**Issue by tonysneed** [TrackableEntities/TrackableEntities.Core#7]
Port the following libraries to Core:

- TrackableEntities.Client => TrackableEntities.Client.Core

Using NetStandard 2.0 will allow usage by Xamarin: <https://blog.xamarin.com/share-code-net-standard-2-0/>

**Comment by weitzhandler** [comment]
I'd encourage a total rebuild of the client infrastructure, including the `EntityBase` and the `ChangeTrackingCollection`.
We want to cover as many scenarios as possible. The reason is, when dealing with a deep graph, things get out of control with the current implementation, especially when changing relationships.
It also depends a great deal in [our discussion](https://github.com/TrackableEntities/TrackableEntities.Core/issues/10#issuecomment-348706476) about what metadata we can get from the server.

**Comment by tonysneed** [comment]
I no longer have time to add enhancements -- although I will still accept pull requests. I'll re-open this if someone steps forward to offer a PR.

**Comment by cessna048** [comment]
So, what is the solution for moving TrackableEntities.Client-based codebases to .Net Core?

Specifically, I get these warnings with the TrackableEntities.Client 2.5.7 library in my .Net 9 client-side app...

warning NU1701: Package 'TrackableEntities.Client 2.5.7' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net9.0'. This package may not be fully compatible with your project.

**Comment by Jaben** [comment]
> So, what is the solution for moving TrackableEntities.Client-based codebases to .Net Core?
> 
> Specifically, I get these warnings with the TrackableEntities.Client 2.5.7 library in my .Net 9 client-side app...
> 
> warning NU1701: Package 'TrackableEntities.Client 2.5.7' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net9.0'. This package may not be fully compatible with your project.

Please do not add-on to existing closed issues. Open a new issue if you have questions.
